# mysql:
#      image: mysql:5.7
#      container_name: mysql
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: somepass
#        MYSQL_DATABASE: devqual
#        MYSQL_USER: demo_user
#        MYSQL_PASSWORD: demo_pass    

# web:
#     container_name: web
#     working_dir: /app
#     build: .
#     links: 
#        - "mysql:mysql"
#     dockerfile: src/main/docker/Dockerfile
#     ports:
#       - 
#       - "8080:8080"
#     
version: '2.1'

services: 
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  webapp:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306